### ISSUE TITLE
Uncaught TypeError: _.where is not a function

### ISSUE THREAD

**Issue by chasewalden** [Floobits/floobits-atom#105]
[Enter steps to reproduce below:]

(Created a workspace and I am the only person in it)
1. Command+Shift+P
2. Type: "Floobits video source"
3. Try and use my built in FaceTime camera.
4. This causes an exception

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.0
### Stack Trace

Uncaught TypeError: _.where is not a function

```
At /Users/chase/.atom/packages/floobits/lib/media_sources.js:27

TypeError: _.where is not a function
    at MediaSources.confirmed (/Users/chase/.atom/packages/floobits/lib/media_sources.js:27:20)
    at MediaSources.module.exports.SelectListView.confirmSelection (/Users/chase/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Users/chase/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Users/chase/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Users/chase/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:05.6.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -1:03.5.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:56.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:56.5.0 Floobits: Create Workspace (atom-text-editor.editor.mini)
     -0:45.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
  2x -0:26.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:03.0 Floobits: Video Source (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "floobits": {}
}
```
### Installed Packages

``` coffee
# User
build, v0.54.1
build-cargo, v0.12.0
floobits, v0.31.0
language-rust, v0.4.6
linter, v1.11.3
linter-rust, v0.4.0
racer, v0.18.0

# Dev
No dev packages
```

**Comment by freemanoid** [comment]
Hey @ggreer could you make a release with this fix?
