### ISSUE TITLE
Uncaught TypeError: Cannot read property 'populated' of undefined

### ISSUE THREAD

**Issue by jayterwahl** [Floobits/floobits-atom#106]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.0
### Stack Trace

Uncaught TypeError: Cannot read property 'populated' of undefined

```
At /Users/home/.atom/packages/floobits/lib/common/buffer_model.js:257

TypeError: Cannot read property 'populated' of undefined
    at Collection.flux.createCollection.on_saved (/Users/home/.atom/packages/floobits/lib/common/buffer_model.js:257:11)
    at Action_.<anonymous> (/Users/home/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:56:7)
    at Object.each (/Users/home/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
    at Action_.Emitter.emit (/Users/home/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:55:9)
    at Action_.action_action (/Users/home/.atom/packages/floobits/node_modules/flukes/lib/actions.js:30:21)
    at that.onMessaged_ (/Users/home/.atom/packages/floobits/lib/common/floop.js:166:7)
    at /Users/home/.atom/packages/floobits/lib/common/emitter.js:58:7
    at /Users/home/.atom/packages/floobits/node_modules/lodash/lodash.js:4127:15
    at baseForOwn (/Users/home/.atom/packages/floobits/node_modules/lodash/lodash.js:2639:24)
    at /Users/home/.atom/packages/floobits/node_modules/lodash/lodash.js:4096:18
    at Function.forEach (/Users/home/.atom/packages/floobits/node_modules/lodash/lodash.js:7768:11)
    at Transport.Emitter.emit._.each [as emit] (/Users/home/.atom/packages/floobits/lib/common/emitter.js:57:5)
    at Transport.data_handler_ (/Users/home/.atom/packages/floobits/lib/transport.js:33:10)
    at TLSSocket.that.onData_ (/Users/home/.atom/packages/floobits/lib/transport.js:66:10)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```
### Commands

```
     -5:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -5:03.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:01.6.0 Floobits: Leave Workspace (atom-text-editor.editor)
     -4:57.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:54.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:54.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:48 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  3x -4:08.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:05.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:04.9.0 core:close (atom-text-editor.editor.is-focused)
     -2:21.3.0 tree-view:add-file (span.name.icon.icon-repo)
     -0:38.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:33.9.0 Floobits: Join Workspace (atom-text-editor.editor)
     -0:30.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.9.0 core:close (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
floobits, v0.31.0
language-babel, v2.15.4
linter, v1.11.3

# Dev
No dev packages
```

sup

**Comment by ggreer** [comment]
How this happens: user 1 deletes a buffer. user 2 saves that buffer id. server forwards the saved event and breaks user 1's setup
