### ISSUE TITLE
Uncaught TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by seangates** [Floobits/floobits-atom#109]
[Enter steps to reproduce below:]
1. Attempt to close "Floobits Conflicts"

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.0
### Stack Trace

Uncaught TypeError: Cannot read property 'color' of undefined

```
At /Users/sgates/.atom/packages/floobits/lib/atom_listener.js:289

TypeError: Cannot read property 'color' of undefined
    at AtomListener.on_floobits_highlight (/Users/sgates/.atom/packages/floobits/lib/atom_listener.js:289:48)
    at /Users/sgates/.atom/packages/floobits/lib/atom_listener.js:761:10
    at Action_.<anonymous> (/Users/sgates/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:56:7)
    at Object.each (/Users/sgates/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
    at Action_.Emitter.emit (/Users/sgates/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:55:9)
    at Action_.action_action (/Users/sgates/.atom/packages/floobits/node_modules/flukes/lib/actions.js:30:21)
    at that.onMessaged_ (/Users/sgates/.atom/packages/floobits/lib/common/floop.js:166:7)
    at /Users/sgates/.atom/packages/floobits/lib/common/emitter.js:58:7
    at /Users/sgates/.atom/packages/floobits/node_modules/lodash/lodash.js:4143:15
    at baseForOwn (/Users/sgates/.atom/packages/floobits/node_modules/lodash/lodash.js:2669:24)
    at /Users/sgates/.atom/packages/floobits/node_modules/lodash/lodash.js:4112:18
    at Function.forEach (/Users/sgates/.atom/packages/floobits/node_modules/lodash/lodash.js:7828:11)
    at Transport.Emitter.emit._.each [as emit] (/Users/sgates/.atom/packages/floobits/lib/common/emitter.js:57:5)
    at Transport.data_handler_ (/Users/sgates/.atom/packages/floobits/lib/transport.js:33:10)
    at TLSSocket.that.onData_ (/Users/sgates/.atom/packages/floobits/lib/transport.js:66:10)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.11
autocomplete-css, v0.11.0
autocomplete-html, v0.7.2
autocomplete-plus, v2.23.0
autocomplete-snippets, v1.7.1
docblockr, v0.7.3
file-icons, v1.6.11
floobits, v0.31.0
language-marko, v0.4.17
linter, v1.5.0
linter-jshint, v1.1.5
minimap, v4.10.0
project-manager, v1.15.8

# Dev
No dev packages
```

**Comment by seangates** [comment]
Maybe this was because some of the other packages were outdated? I don't get it now after updating Atom, and the other packages I had installed.
