### ISSUE TITLE
Uncaught Error: Unknown call format to patch_make.

### ISSUE THREAD

**Issue by columna1** [Floobits/floobits-atom#110]
not completely sure how to reproduce
files were deleted wrongfully and when I restored them I got this error

**Atom Version**: 1.6.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.0
### Stack Trace

Uncaught Error: Unknown call format to patch_make.

```
At C:\Users\Columna1\.atom\packages\floobits\node_modules\dmp\lib\dmp.js:1665

Error: Unknown call format to patch_make.
    at FlooDMP.diff_match_patch.patch_make (C:\Users\Columna1\.atom\packages\floobits\node_modules\dmp\lib\dmp.js:1665:11)
    at Model.Buffer.send_patch (C:\Users\Columna1\.atom\packages\floobits\lib\common\buffer_model.js:79:17)
    at FSWatcher.<anonymous> (C:\Users\Columna1\.atom\packages\floobits\lib\atom_listener.js:641:17)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (C:\Users\Columna1\.atom\packages\floobits\node_modules\chokidar\index.js:171:15)
    at awfEmit (C:\Users\Columna1\.atom\packages\floobits\node_modules\chokidar\index.js:188:9)
    at FSWatcher.<anonymous> (C:\Users\Columna1\.atom\packages\floobits\node_modules\chokidar\index.js:290:9)
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
floobits, v0.31.0
language-lua, v0.9.4
Sublime-Style-Column-Selection, v1.3.0
term3, v0.21.4

# Dev
No dev packages
```

**Comment by a-eid** [comment]
+1 same issue 

I'm however using `ubuntu 17.04` my pair is using window 10

**Comment by DoubleCouponDay** [comment]
Im getting this randomly. I cant see any pattern where my user actions causes it.

windows 10, 64 bit

packages:
```
autocomplete-python 1.1.5
busy-signal.1.4.3
floobits 0.32.12
intentions 1.1.5
python-indent 1.1.4
python-tools 0.6.9
```
