### ISSUE TITLE
Failed to load the floobits package

### ISSUE THREAD

**Issue by franciscoInnomius** [Floobits/floobits-atom#111]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.1
### Stack Trace

Failed to load the floobits package

```
At Cannot find module 'request'

Error: Cannot find module 'request'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/franciscohuizar/.atom/packages/floobits/lib/common/api.js:6:17)
    at Module._compile (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/franciscohuizar/.atom/packages/floobits/lib/floobits.js:13:13)
    at Module._compile (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/franciscohuizar/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
floobits, v0.31.1
jshint, v1.8.3
react-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by ggreer** [comment]
`request` is in `package.json`, so I'm not sure how this could fail. Maybe Atom died during the installation or something? Can you try uninstalling and reinstalling the floobits package? I think that will fix this.

**Comment by jayterwahl** [comment]
Reinstalling fixed the problem for me.
