### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validated' of undefined

### ISSUE THREAD

**Issue by trusktr** [Floobits/floobits-atom#121]
[Enter steps to reproduce below:]
1. I just open the file tree and this error is thrown.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.2
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.3
### Stack Trace

Uncaught TypeError: Cannot read property 'validated' of undefined

```
At /Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactDescriptor.js:217

TypeError: Cannot read property 'validated' of undefined
    at Function.ReactDescriptor.cloneAndReplaceProps (/Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactDescriptor.js:217:38)
    at [object Object].ReactComponent.Mixin.replaceProps (/Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactComponent.js:182:49)
    at /Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:245:21
    at Object.ReactMount.scrollMonitor (/Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:228:5)
    at Object.ReactMount._updateRootComponent (/Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:244:16)
    at Object.ReactMount.renderComponent (/Users/trusktr/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:362:27)
    at terminal-list-view.HTMLElementProto.attachedCallback (/Users/trusktr/.atom/packages/term3/lib/build/list-view.js:54:26)
    at atom-panel-container.PanelContainerElement.panelAdded (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/panel-container-element.js:46:14)
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PanelContainer.module.exports.PanelContainer.addPanel (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/panel-container.js:69:20)
    at Workspace.module.exports.Workspace.addPanel (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/workspace.js:893:45)
    at Workspace.module.exports.Workspace.addLeftPanel (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/workspace.js:826:19)
    at TreeView.module.exports.TreeView.attach (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:429:27)
    at TreeView.module.exports.TreeView.show (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:419:12)
    at TreeView.module.exports.TreeView.toggle (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:414:21)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/main.js:32:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:04.1.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.4.0 tree-view:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:02.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:02.1.0 tree-view:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:01.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:00.9.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:00.4.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "vim-mode-plus-move-to-symbols",
      "vim-mode-plus-move-selected-text",
      "vim-mode-plus-project-find-from-search",
      "todo-show",
      "language-yaml",
      "language-toml",
      "language-xml",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "welcome",
      "vim-mode-plus-ex-mode",
      "ex-mode"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.4.4
floobits, v0.31.3
minimap, v4.24.4
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
nerd-treeview, v0.4.2
nucleus-dark-ui, v0.8.3
pigments, v0.29.2
project-plus, v0.9.0
term3, v0.22.0
todo-manager, v0.2.9
vim-mode-plus, v0.44.1
vim-mode-visual-block, v0.2.15

# Dev
No dev packages
```

**Comment by trusktr** [comment]
This happens when I open the file tree.

**Comment by trusktr** [comment]
@kans @ggreer Can you take a look at this? This error is extremely annoying.

**Comment by ggreer** [comment]
This is a bug in Atom. Atom is erasing the NODE_ENV environment variable some point after startup, which causes React to run in development mode. If React initially runs in production mode, then changes to dev mode (because NODE_ENV was erased), it will crash.

I've created a workaround in term3. Please upgrade that package to v0.22.1.

**Comment by ggreer** [comment]
Closing this because the Atom bug was fixed.
