### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by HeshamAbdalla** [Floobits/floobits-atom#127]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.3
### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:510

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:510:50)
    at findParent (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactEventListener.js:46:30)
    at handleTopLevelImpl (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactEventListener.js:81:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/Transaction.js:141:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
    at Object.batchedUpdates (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactUpdates.js:113:20)
    at ReactEventListener.dispatchEvent (/Users/heshamabdalla/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactEventListener.js:186:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "firewatch-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
firewatch-syntax, v1.0.1
floobits, v0.31.3
seti-ui, v1.3.1

# Dev
No dev packages
```

**Comment by ggreer** [comment]
This is the same underlying issue as #121 and #123. If you launch Atom from the command line, it can erase the `NODE_ENV` environment variable. This can break React: https://github.com/atom/atom/issues/12024

I've submitted a fix: https://github.com/atom/atom/pull/12028

I'm waiting on Atom devs to approve/comment/etc.

**Comment by HeshamAbdalla** [comment]
Thank you 👍
