### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by Finsaas** [Floobits/floobits-atom#128]
[Enter steps to reproduce below:]
1. ...leave an active workspace
2. ...try to close Term3

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.31.3
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of null

```
At /Users/Finsaas/.atom/packages/floobits/lib/terminal_manager.js:117

TypeError: Cannot read property 'remove' of null
    at /Users/Finsaas/.atom/packages/floobits/lib/terminal_manager.js:117:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TermView.destroy (/Users/Finsaas/.atom/packages/term3/lib/term-view.coffee:255:16)
    at /Users/Finsaas/.atom/packages/term3/index.coffee:190:14
    at Function.module.exports.Emitter.simpleDispatch (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:551:20)
    at Pane.module.exports.Pane.destroyItem (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Users/Finsaas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```
### Commands

```
  3x -9:04.8.0 core:confirm (ul.list-inline.tab-bar.inset-panel)
     -0:16.3.0 Floobits: Leave Workspace (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
floobits, v0.31.3
term3, v0.22.1

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Fixed in #130. Released in v0.32.1.
