### ISSUE TITLE
Uncaught TypeError: offsetIndex.totalTo is not a function

### ISSUE THREAD

**Issue by rulonsw** [Floobits/floobits-atom#145]
[Enter steps to reproduce below:]

1. Click a line on any open file in a Floobits workspace.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.32.7

### Stack Trace

Uncaught TypeError: offsetIndex.totalTo is not a function

```
At /Users/rulon.wood/.atom/packages/floobits/lib/atom_utils.js:32

TypeError: offsetIndex.totalTo is not a function
    at Object.offsetToBufferRange (/Users/rulon.wood/.atom/packages/floobits/lib/atom_utils.js:32:34)
    at /Users/rulon.wood/.atom/packages/floobits/lib/atom_listener.js:310:24
    at arrayMap (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:9571:14)
    at /Users/rulon.wood/.atom/packages/floobits/lib/atom_listener.js:306:7
    at arrayEach (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:9359:14)
    at AtomListener.on_floobits_highlight (/Users/rulon.wood/.atom/packages/floobits/lib/atom_listener.js:293:5)
    at /Users/rulon.wood/.atom/packages/floobits/lib/atom_listener.js:791:10
    at Action_.<anonymous> (/Users/rulon.wood/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:56:7)
    at Object.each (/Users/rulon.wood/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
    at Action_.Emitter.emit (/Users/rulon.wood/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:55:9)
    at Action_.action_action (/Users/rulon.wood/.atom/packages/floobits/node_modules/flukes/lib/actions.js:30:21)
    at that.onMessaged_ (/Users/rulon.wood/.atom/packages/floobits/lib/common/floop.js:167:7)
    at _.each (/Users/rulon.wood/.atom/packages/floobits/lib/common/emitter.js:58:7)
    at /Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:3001:24)
    at /Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/rulon.wood/.atom/packages/floobits/node_modules/lodash/lodash.js:9359:14)
    at Transport.Emitter.emit (/Users/rulon.wood/.atom/packages/floobits/lib/common/emitter.js:57:5)
    at Transport.data_handler_ (/Users/rulon.wood/.atom/packages/floobits/lib/transport.js:33:10)
    at TLSSocket.that.onData_ (/Users/rulon.wood/.atom/packages/floobits/lib/transport.js:66:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
```

### Commands

```
     -3:05.4.0 settings-view:open (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -2:11.4.0 core:backspace (input.hidden-input)
     -1:49.6.0 find-and-replace:focus-next (input.hidden-input)
  4x -1:48.1.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
floobits, v0.32.7 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ggreer** [comment]
My atom-beta's auto-updater was broken, so I didn't see this early. Should be fixed in v0.32.8.
