### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by valentin-blank** [Floobits/floobits-atom#151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.8.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package 0.32.9

### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At /Users/rozlav/.atom/packages/floobits/node_modules/fuzzaldrin/lib/scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (/packages/floobits/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (/packages/floobits/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (/packages/floobits/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at DirectorySelectorView.module.exports.SelectListView.populateList (/packages/floobits/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at /packages/floobits/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
  2x -1:43.9.0 Floobits: Join Workspace (input.hidden-input)
     -0:22.2.0 core:select-all (input#floobits-url.native-key-bindings.form-control)
     -0:21.9.0 core:copy (input#floobits-url.native-key-bindings.form-control)
     -0:08.7.0 Floobits: Join Workspace (atom-workspace.workspace.theme-one-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -0:08.0 core:paste (input.hidden-input)
     -0:06.3.0 core:select-all (input.hidden-input)
     -0:05.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
auto-indent 0.5.0 
emmet 2.4.3 
floobits 0.32.9 
indent-guide-ext 0.2.3 
indent-guide-improved 1.4.12 
```

**Comment by bdodroid** [comment]
I'm having the same issue.
Running Atom on Ubuntu 16.10
