### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by luisrudge** [Floobits/floobits-atom#35]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Luis\.atom\packages\floobits\lib\common\webrtc.js:250

TypeError: Cannot read property 'id' of undefined
  at WebRTC.myConnId_ (C:\Users\Luis\.atom\packages\floobits\lib\common\webrtc.js:250:35)
  at WebRTC.stopVideo (C:\Users\Luis\.atom\packages\floobits\lib\common\webrtc.js:789:12)
  at Action_.<anonymous> (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:56:7)
  at Object.each (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\utils.js:73:16)
  at Action_.Emitter.emit (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:55:9)
  at Action_.action_action (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\actions.js:30:21)
  at FlooHandler.on_part (C:\Users\Luis\.atom\packages\floobits\lib\common\handlers\floohandler.js:412:16)
  at Action_.<anonymous> (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:56:7)
  at Object.each (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\utils.js:73:16)
  at Action_.Emitter.emit (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:55:9)
  at Action_.action_action (C:\Users\Luis\.atom\packages\floobits\node_modules\flukes\lib\actions.js:30:21)
  at that.onMessaged_ (C:\Users\Luis\.atom\packages\floobits\lib\common\floop.js:155:7)
  at Transport.<anonymous> (C:\Users\Luis\.atom\packages\floobits\lib\common\emitter.js:58:7)
  at C:\Users\Luis\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:2945:23
  at C:\Users\Luis\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3167:15
  at baseForOwn (C:\Users\Luis\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:2095:14)
  at C:\Users\Luis\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3137:18
  at Function.<anonymous> (C:\Users\Luis\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3414:13)
  at Transport.Emitter.emit (C:\Users\Luis\.atom\packages\floobits\lib\common\emitter.js:57:5)
  at Transport.data_handler_ (C:\Users\Luis\.atom\packages\floobits\lib\transport.js:33:10)
  at TLSSocket.that.onData_ (C:\Users\Luis\.atom\packages\floobits\lib\transport.js:66:10)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:109:10)
  at TLSWrap.onread (net.js:517:20)

```
### Commands

```
     -6:04.7.0 application:open-folder (atom-pane.pane.active)
  2x -6:04.7.0 command-palette:toggle (atom-pane.pane.active)
  4x -6:01.6.0 core:move-down (atom-text-editor.editor.mini)
     -6:00.8.0 core:confirm (atom-text-editor.editor.mini)
     -6:00.8.0 floobits: join workspace (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-typescript-tools, v0.6.2
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
bezier-curve-editor, v0.6.6
color-picker, v1.7.0
css-snippets, v0.8.0
editorconfig, v1.0.0
emmet, v2.3.8
floobits, v0.2.0
language-cshtml, v0.1.1
language-css-plus, v0.3.0
language-typescript, v0.15.0
less-than-slash, v0.6.0
linter, v0.12.1
linter-tslint, v0.2.1
minimap, v4.7.6
omnisharp-atom, v0.4.8

# Dev
No dev packages
```

**Comment by ggreer** [comment]
OK, should be fixed in the latest release (0.4.0).
