### ISSUE TITLE
terminals

### ISSUE THREAD

**Issue by kans** [Floobits/floobits-atom#39]
At /floobits/atom-floobits/lib/common/terminal_model.js:83

ReferenceError: Terminal is not defined
    at Collection.flux.createCollection.addTerminal (/floobits/atom-floobits/lib/common/terminal_model.js:83:16)
    at Collection.<anonymous> (/floobits/atom-floobits/lib/common/terminal_model.js:35:12)
    at Action_.<anonymous> (/floobits/atom-floobits/node_modules/flukes/lib/emitter.js:56:7)
    at Object.each (/floobits/atom-floobits/node_modules/flukes/lib/utils.js:73:16)
    at Action_.Emitter.emit (/floobits/atom-floobits/node_modules/flukes/lib/emitter.js:55:9)
    at Action_.action_action (/floobits/atom-floobits/node_modules/flukes/lib/actions.js:30:21)
    at that.onMessaged_ (/floobits/atom-floobits/lib/common/floop.js:155:7)
    at Transport.<anonymous> (/floobits/atom-floobits/lib/common/emitter.js:58:7)
    at /floobits/atom-floobits/node_modules/lodash/index.js:2945:23
    at /floobits/atom-floobits/node_modules/lodash/index.js:3167:15

```

```

**Comment by ggreer** [comment]
Fixed.
