### ISSUE TITLE
Uncaught TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by yngbldjr** [Floobits/floobits-atom#52]
[Enter steps to reproduce below:]
1. Join a workspace
2. Leave a workspace

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.10.4
### Stack Trace

Uncaught TypeError: Cannot read property 'write' of null

```
At /Users/carter/.atom/packages/floobits/lib/common/floop.js:195

TypeError: Cannot read property 'write' of null
  at Action_.Actions.send_ (/Users/carter/.atom/packages/floobits/lib/common/floop.js:195:17)
  at Action_.actionOut (/Users/carter/.atom/packages/floobits/lib/common/floop.js:89:10)
  at Action_.action_action (/Users/carter/.atom/packages/floobits/node_modules/flukes/lib/actions.js:26:31)
  at AtomListener.onDidChangeSelectionRange (/Users/carter/.atom/packages/floobits/lib/atom_listener.js:118:11)
  at action (/Users/carter/.atom/packages/floobits/lib/atom_listener.js:182:23)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2112:27)
  at Selection.module.exports.Selection.screenRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:911:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:43:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at DisplayBuffer.module.exports.DisplayBuffer.refreshMarkerScreenPositions (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1509:16)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:315:14)
  at DisplayBuffer.module.exports.DisplayBuffer.updateWrappedScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:330:19)
  at DisplayBuffer.module.exports.DisplayBuffer.setWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:467:14)
  at TextEditor.module.exports.TextEditor.setWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2799:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setContentFrameWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1171:20)
  at TextEditorComponent.module.exports.TextEditorComponent.measureDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:844:24)
  at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:804:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
  at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:217:9)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:179:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```
### Commands

```
     -2:43.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:43.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:43.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:43.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:43.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:42.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:42.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:42.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:40.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:18 core:copy (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:42.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:03.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 Floobits: Leave Workspace (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "term",
      "scala-format",
      "term2",
      "slack-chat",
      "slack-atom",
      "scala-worksheet"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Ensime, v0.23.0
cursor-history, v0.4.18
floobits, v0.10.4
language-scala, v1.1.3
language-scala-plus, v1.2.2
last-cursor-position, v0.9.0
markdown-preview-plus, v1.7.0
pretty-json, v0.4.1
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Thanks for reporting this. The latest version (0.10.5) should do a better job of handling disconnects.
