### ISSUE TITLE
Uncaught Error: Create buf for existing buffer:

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-atom#54]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.8-24b4979
**System**: Mac OS X 10.10.5
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.11.2
### Stack Trace

Uncaught Error: Create buf for existing buffer:

```
At /Users/ggreer/floobits/atom-plugin/lib/atom_listener.js:556

Error: Create buf for existing buffer:
  at /Users/ggreer/floobits/atom-plugin/lib/atom_listener.js:556:13
  at Action_.<anonymous> (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/emitter.js:56:7)
  at Object.each (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/utils.js:73:16)
  at Action_.Emitter.emit (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/emitter.js:55:9)
  at Action_.action_action (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/actions.js:30:21)
  at Collection.flux.createCollection.add (/Users/ggreer/floobits/atom-plugin/lib/common/buffer_model.js:273:18)
  at Collection.flux.createCollection.on_create_buf (/Users/ggreer/floobits/atom-plugin/lib/common/buffer_model.js:250:10)
  at Action_.<anonymous> (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/emitter.js:56:7)
  at Object.each (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/utils.js:73:16)
  at Action_.Emitter.emit (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/emitter.js:55:9)
  at Action_.action_action (/Users/ggreer/floobits/atom-plugin/node_modules/flukes/lib/actions.js:30:21)
  at that.onMessaged_ (/Users/ggreer/floobits/atom-plugin/lib/common/floop.js:154:7)
  at Transport.<anonymous> (/Users/ggreer/floobits/atom-plugin/lib/common/emitter.js:58:7)
  at /Users/ggreer/floobits/atom-plugin/node_modules/lodash/index.js:2874:23
  at /Users/ggreer/floobits/atom-plugin/node_modules/lodash/index.js:3073:15
  at baseForOwn (/Users/ggreer/floobits/atom-plugin/node_modules/lodash/index.js:2046:14)
  at /Users/ggreer/floobits/atom-plugin/node_modules/lodash/index.js:3043:18
  at Function.<anonymous> (/Users/ggreer/floobits/atom-plugin/node_modules/lodash/index.js:3346:13)
  at Transport.Emitter.emit (/Users/ggreer/floobits/atom-plugin/lib/common/emitter.js:57:5)
  at Transport.data_handler_ (/Users/ggreer/floobits/atom-plugin/lib/transport.js:33:10)
  at TLSSocket.that.onData_ (/Users/ggreer/floobits/atom-plugin/lib/transport.js:66:10)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:109:10)
  at TLSWrap.onread (net.js:517:20)

```
### Commands

```
     -7:26.3.0 core:close (div.settings-view.pane-item)
     -7:24.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:22.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:22.4.0 Floobits: Summon (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "atom-plugin",
      "metrics"
    ]
  },
  "floobits": {
    "atoms-api-sucks-url": "https://floobits.com/Floobits/colab",
    "mugshots": true,
    "showNotifications": false
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kans** [comment]
likely fixed by 0f162b9

**Comment by Gurkenglas** [comment]
Nope, I'm on 0.15.0 and it just happened for me:

Error: Create buf for existing buffer:
    at C:\Users\Gurkenglas.atom\packages\floobits\lib\atom_listener.js:581:13
    at Action_.<anonymous> (C:\Users\Gurkenglas.atom\packages\floobits\node_modules\flukes\lib\emitter.js:56:7)
    at Object.each (C:\Users\Gurkenglas.atom\packages\floobits\node_modules\flukes\lib\utils.js:73:16)
    at Action_.Emitter.emit (C:\Users\Gurkenglas.atom\packages\floobits\node_modules\flukes\lib\emitter.js:55:9)
    at Action_.action_action (C:\Users\Gurkenglas.atom\packages\floobits\node_modules\flukes\lib\actions.js:30:21)
    at Collection.flux.createCollection.add (C:\Users\Gurkenglas.atom\packages\floobits\lib\common\buffer_model.js:275:18)
    at FlooHandler.<anonymous> (C:\Users\Gurkenglas.atom\packages\floobits\lib\common\handlers\floohandler.js:241:15)
    at C:\Users\Gurkenglas\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:2874:23
    at C:\Users\Gurkenglas\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3073:15
    at baseForOwn (C:\Users\Gurkenglas\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:2046:14)

I joined a workspace with a lot of files on my side that I didn't want uploaded and a few on the other side I needed to get, so I told it to overwrite local files. It froze after a few seconds. The next day (standby mode in between I think), it was done but that error popped up.

**Comment by kans** [comment]
@Gurkenglas 

Thanks for the report.  I'm looking into it.

**Comment by kans** [comment]
@Gurkenglas 
This should be fixed in the latest release as well as quite a few other bugs.
