### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Awarua-** [Floobits/floobits-atom#66]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.14.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\wooll\.atom\packages\floobits\lib\atom_listener.js:551

TypeError: undefined is not a function
    at C:\Users\wooll\.atom\packages\floobits\lib\atom_listener.js:551:31
    at Action_.<anonymous> (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:56:7)
    at Object.each (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\utils.js:73:16)
    at Action_.Emitter.emit (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:55:9)
    at Action_.action_action (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\actions.js:30:21)
    at Collection.flux.createCollection.on_rename_buf (C:\Users\wooll\.atom\packages\floobits\lib\common\buffer_model.js:259:18)
    at Action_.<anonymous> (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:56:7)
    at Object.each (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\utils.js:73:16)
    at Action_.Emitter.emit (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\emitter.js:55:9)
    at Action_.action_action (C:\Users\wooll\.atom\packages\floobits\node_modules\flukes\lib\actions.js:30:21)
```
### Commands

```
     -8:46.7.0 Floobits: Join Workspace (atom-pane.pane.active)
     -8:43.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:29.1.0 core:save (atom-text-editor.editor.is-focused)
     -8:05.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:47.4.0 core:save (atom-text-editor.editor.is-focused)
  7x -5:18.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:08.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:08.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
floobits, v0.14.0

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Sorry about that. The latest version (0.14.1) should have this fixed. Thanks for reporting this bug.
