### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by dalanmiller** [Floobits/floobits-atom#84]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.27.0
### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /Users/dalanmiller/.atom/packages/floobits/lib/atom_listener.js:608

TypeError: Cannot read property 'push' of undefined
  at /Users/dalanmiller/.atom/packages/floobits/lib/atom_listener.js:608:37
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at /Users/dalanmiller/.atom/packages/floobits/lib/atom_listener.js:607:7
  at Action_.<anonymous> (/Users/dlaanmiller/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:56:7)
  at Object.each (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
  at Action_.Emitter.emit (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:55:9)
  at Action_.action_action (/Users/dlaanmiller/.atom/packages/floobits/node_modules/flukes/lib/actions.js:30:21)
  at Collection.flux.createCollection.on_delete_buf (/Users/dalanmiller/.atom/packages/floobits/lib/common/buffer_model.js:290:18)
  at Action_.<anonymous> (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:56:7)
  at Object.each (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
  at Action_.Emitter.emit (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:55:9)
  at Action_.action_action (/Users/dalanmiller/.atom/packages/floobits/node_modules/flukes/lib/actions.js:30:21)
  at that.onMessaged_ (/Users/dalanmiller/.atom/packages/floobits/lib/common/floop.js:166:7)
  at Transport.<anonymous> (/Users/dalanmiller/.atom/packages/floobits/lib/common/emitter.js:58:7)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:2874:23
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3073:15
  at baseForOwn (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:2046:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3043:18
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3346:13)
  at Transport.Emitter.emit (/Users/dalanmiller/.atom/packages/floobits/lib/common/emitter.js:57:5)
  at Transport.data_handler_ (/Users/dalanmiller/.atom/packages/floobits/lib/transport.js:33:10)
  at TLSSocket.that.onData_ (/Users/dalanmiller/.atom/packages/floobits/lib/transport.js:66:10)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:110:10)
  at TLSWrap.onread (net.js:520:20)

```
### Commands

```
     -4:02.9.0 core:close (atom-pane.pane.active)
  4x -1:24.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:21 core:save (atom-text-editor.editor.is-focused)
     -1:17.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:15.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:13.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:13.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-dark-syntax"
    ]
  },
  "floobits": {
    "mugshots": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.15
floobits, v0.27.0
go-plus, v3.5.1
linter-golinter, v1.0.0
term3, v0.19.0

# Dev
No dev packages
```

**Comment by kans** [comment]
Thanks for the report.  Did this just happen in normal usage?

**Comment by dalanmiller** [comment]
Yeah, just installed for the first time and this came up.

**Comment by kans** [comment]
@dalanmiller 
I just pushed the updated package.
