### ISSUE TITLE
Uncaught Error: Invariant Violation: forceUpdate(...): Cannot force an update while unmounting co...

### ISSUE THREAD

**Issue by jeffreywescott** [Floobits/floobits-atom#87]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.29.0
### Stack Trace

Uncaught Error: Invariant Violation: forceUpdate(...): Cannot force an update while unmounting component or during an existing state transition (such as within `render`).

```
At /Users/jeffrey/.atom/packages/floobits/node_modules/react-atom-fork/lib/invariant.js:56

Error: Invariant Violation: forceUpdate(...): Cannot force an update while unmounting component or during an existing state transition (such as within `render`).
    at invariant (/Users/jeffrey/.atom/packages/floobits/node_modules/react-atom-fork/lib/invariant.js:49:15)
    at [object Object].ReactCompositeComponentMixin.forceUpdate (/Users/jeffrey/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1224:46)
    at [object Object].update (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/autobinder.js:62:14)
    at Users.<anonymous> (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:51:7)
    at Object.each (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
    at Users.Emitter.emit (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:50:9)
    at Users.DataEmitter.update (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/data_emitter.js:52:13)
    at Users.<anonymous> (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/collections.js:68:10)
    at User.<anonymous> (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/emitter.js:51:7)
    at Object.each (/Users/jeffrey/.atom/packages/floobits/node_modules/flukes/lib/utils.js:73:16)
```
### Commands

```
     -1:07.0 command-palette:toggle (atom-pane.pane.active)
     -1:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.2.0 Floobits: Join Workspace (atom-pane.pane.active)
     -0:56.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
floobits, v0.29.0
language-cjsx, v0.3.0
language-docker, v1.1.3
language-javascript-jsx, v0.3.7

# Dev
No dev packages
```

**Comment by kans** [comment]
I think this is best fixed upstream in flukes - its easy to check if we've already called forced update in the given update cycle.  Perhaps we shouldn't be calling force update anyway...
