### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tabForItem' of undefined

### ISSUE THREAD

**Issue by raymatos** [Floobits/floobits-atom#88]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.29.0
### Stack Trace

Uncaught TypeError: Cannot read property 'tabForItem' of undefined

```
At /Users/raymatos/.atom/packages/floobits/templates/pane.coffee:15

TypeError: Cannot read property 'tabForItem' of undefined
    at /Users/raymatos/.atom/packages/floobits/templates/pane.coffee:15:34
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
  5x -1:57.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:56.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:56.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:55.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:55.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:55.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:55.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:54.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:54.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:53.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:53.5.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -1:52.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.7.0 Floobits: Join Workspace (atom-text-editor.editor.is-focused)
     -0:02.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
floobits, v0.29.0
language-erlang, v3.0.0
motepair, v0.21.0

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Please try our latest release (v0.29.1). It should be fixed now.
