### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

### ISSUE THREAD

**Issue by ruuts** [Floobits/floobits-atom#93]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.29.3
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at Object.module.exports.join_workspace_ (/Users/ruud/.atom/packages/floobits/lib/floobits.js:426:15)
    at Object.require.on_url (/Users/ruud/.atom/packages/floobits/lib/floobits.js:410:12)
    at [object Object].<anonymous> (/Users/ruud/.atom/packages/floobits/lib/build/join.js:23:18)
```
### Commands

```
     -6:28.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -6:24.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:23.8.0 AtomPair:join pairing session (atom-text-editor.editor)
     -6:23.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -6:23 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:45.4.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
  4x -1:40.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:39.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:39.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.1.0 Floobits: Join Workspace (atom-text-editor#AtomPair.editor)
 11x -0:21.4.0 core:paste (input#floobits-url.native-key-bindings.form-control)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
floobits, v0.29.3
motepair, v0.21.0

# Dev
No dev packages
```

**Comment by Stenudd** [comment]
Same here

Windows 8.1 Pro, 64-bit

Error: ENOENT: no such file or directory, lstat 'C:\Users<User>\AppData\Local\atom\app-1.5.3\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at Object.module.exports.join_workspace_ (C:\Users<User>.atom\packages\floobits\lib\floobits.js:427:15)
    at Object.require.on_url (C:\Users<User>.atom\packages\floobits\lib\floobits.js:411:12)
    at [object Object].<anonymous> (C:\Users<User>.atom\packages\floobits\lib\build\join.js:23:18)

**Comment by Stenudd** [comment]
Problem seems to be that "Select Directory" is set to atom://config and can't be changed. Generating the error that it cannot find "atom:", notice the extra colon at the end.

http://i.imgur.com/Doywx03.png

**Comment by Stenudd** [comment]
And that seems to come from that atom have created an unnamed project folder, or rather named it atom://config, showing as "config" on left side panel. Right clicking on config and select "Remove Project Folder" seems to solve the problem. You can now select a new folder for floobits join.
