### ISSUE TITLE
Uncaught TypeError: Cannot set property '.0' of undefined

### ISSUE THREAD

**Issue by dustinblackman** [Floobits/floobits-atom#94]
## Reproduce
1. Open new window

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.29.3
### Stack Trace

Uncaught TypeError: Cannot set property '.0' of undefined

```
At /Users/dustinblackman/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:321

TypeError: Cannot set property '.0' of undefined
    at Object._renderNewRootComponent (/Users/dustinblackman/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:321:48)
    at Object.ReactMount.renderComponent (/Users/dustinblackman/.atom/packages/floobits/node_modules/react-atom-fork/lib/ReactMount.js:379:32)
    at terminal-list-view.HTMLElementProto.attachedCallback (/Users/dustinblackman/.atom/packages/term3/lib/build/list-view.js:50:26)
    at atom-panel-container.PanelContainerElement.panelAdded (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container-element.js:46:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PanelContainer.module.exports.PanelContainer.addPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/panel-container.js:69:20)
    at Workspace.module.exports.Workspace.addPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:824:45)
    at Workspace.module.exports.Workspace.addLeftPanel (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:773:19)
    at TreeView.module.exports.TreeView.attach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:419:27)
    at TreeView.module.exports.TreeView.updateRoots (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:578:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:361:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1026:26)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:201:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:02.9.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "floobits": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-material-ui, v0.8.0
atom-minify, v0.6.2
atom-ternjs, v0.11.3
autoclose-html, v0.19.0
autocomplete-bibtex, v0.6.1
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
circle-ci, v0.10.1
color-picker, v2.0.14
file-icons, v1.6.13
floobits, v0.29.3
highlight-line, v0.11.0
htmlhint, v1.1.3
hyperclick, v0.0.35
language-cjsx, v0.3.0
language-diff, v0.4.0
language-docker, v1.1.6
language-ect, v0.2.0
language-ejs, v0.2.0
language-jade, v0.6.2
language-lua, v0.9.4
language-pgsql, v0.2.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-erb, v0.1.1
linter-eslint, v5.2.6
linter-jsxhint, v0.1.2
linter-pep8, v1.0.1
linter-stylint, v2.0.1
linter-xmllint, v1.1.0
livereload, v0.4.4
minimap, v4.18.0
minimap-git-diff, v4.1.8
monokai-seti, v0.7.0
node-debugger, v1.3.0
open-recent, v4.0.1
pigments, v0.19.3
react, v0.12.10
semantic-ui, v1.0.7
set-syntax, v0.3.0
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
term3, v0.19.2
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Hmm... this looks like an issue in [react-atom-fork](https://github.com/atom/react/tree/selection-restoration-opt-out). `rootElementsByReactRootID` shouldn't be touched at all unless Atom is being run in debug mode.

**Comment by dustinblackman** [comment]
Odd, not running in debug mode.

**Comment by ggreer** [comment]
Hmm... can you describe how to reproduce this? I'm on OS X 10.11.3 using Atom 1.4.2 and I can't figure out how to trigger this bug.
