### ISSUE TITLE
Uncaught Error: [object Object]

### ISSUE THREAD

**Issue by Rakin05** [Floobits/floobits-atom#97]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Ubuntu 15.10
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.30.0
### Stack Trace

Uncaught Error: [object Object]

```
At /home/felix/.atom/packages/floobits/lib/build/edit_perms_view.js:118

Error: [object Object]
    at Object.ajax.error (/home/felix/.atom/packages/floobits/lib/build/edit_perms_view.js:118:15)
    at fire (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.self.fireWith [as rejectWith] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3211:7)
    at done (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8266:14)
    at XMLHttpRequest.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8605:9)
```
### Commands

```
     -1:39.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.8.0 Floobits: Setup (atom-text-editor.editor.mini)
     -1:28.5.0 core:close (webview.native-key-bindings)
     -1:05.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -1:04.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  6x -1:00.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:59.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.9.0 Floobits: Create Workspace (atom-text-editor.editor)
     -0:59.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:36.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-material-ui)
     -0:31.2.0 command-palette:toggle (atom-pane.pane.active)
     -0:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.9.0 Floobits: Summon (atom-pane.pane.active)
     -0:20.7.0 command-palette:toggle (atom-pane.pane.active)
     -0:17.2.0 Floobits: Permissions (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.8.0
atom-pair, v2.0.10
build, v0.52.0
floobits, v0.30.0
language-haskell, v1.5.2

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Ah, this can happen if an API request fails (either a network issue or Floobits is down). I'll work on a better error handler.

**Comment by ggreer** [comment]
I'll tag a release pretty soon. Sit tight!
