### ISSUE TITLE
"Uncaught Error: EMFILE: too many open files, open..."

### ISSUE THREAD

**Issue by dk0r** [Floobits/floobits-atom#99]
[Enter steps to reproduce below:]
1. Create new floobits workspace via Atom on Windows10
   Ctrl+Shift+P > Floobits: Create Workspace > Select project directory > Create Workspace
2. Incur following error w/in Atom: 
   Screenshot:  http://i.imgur.com/SB6o6pJ.png

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [floobits](https://github.com/Floobits/floobits-atom) package, v0.30.0
### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\user.atom\packages\floobits\node_modules\chokidar\index.js'

```
At fs.js:549

Error: EMFILE: too many open files, open 'C:\Users\user\.atom\packages\floobits\node_modules\chokidar\index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at compileFileAtPath (C:\Users\user\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:207:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\user\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at AtomListener.start_chokidar_ (C:\Users\user\.atom\packages\floobits\lib\atom_listener.js:577:20)
    at Object.args.onHandledConflicts (C:\Users\user\.atom\packages\floobits\lib\atom_listener.js:736:12)
    at [object Object].module.exports.React.createClass.remote_ (C:\Users\user\.atom\packages\floobits\lib\build\conflicts.js:102:16)
    at boundMethod (C:\Users\user\.atom\packages\floobits\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
    at C:\Users\user\.atom\packages\floobits\lib\build\conflicts.js:40:9
```
### Commands

```
     -0:32.7.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:21.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 Floobits: Create Workspace (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:18.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-eslint",
      "linter"
    ]
  },
  "floobits": {
    "audioOnly": true
  }
}
```
### Installed Packages

``` coffee
# User
autohide-tree-view, v0.25.1
browser-plus, v0.0.54
floobits, v0.30.0
indent-guide-improved, v1.4.5
minimap, v4.19.0
minimap-linter, v1.1.1
react, v0.14.1
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by ggreer** [comment]
Hmm... odd that it's uploading `node_modules`. It definitely shouldn't be doing that. :(

Do you have any idea what the file descriptor limit is on your machine? It'd be nice to know if this died because it had 1000 files open or if it died because it had 50,000 open.

**Comment by ggreer** [comment]
OK, I fixed the issue with `node_modules` being uploaded. I'm still not sure what the file descriptor limit is though, so I can't guarantee this bug is fixed.

**Comment by imgnx** [comment]
@ggreer 

Greetings! :)

I got this same error but my machine is trying to work through it.
I wasn't able to view the stack trace.
I'm working in Atom 1.10.2 on Windows 10 Home Edition.
So far, creating a new workspace has opened 4,297 files and it's only at 47%.

Here are some screenshots:

![2016-09-11 1](https://cloud.githubusercontent.com/assets/20768148/18421336/efdbbff8-784d-11e6-888a-a73126303961.png)
![2016-09-11 2](https://cloud.githubusercontent.com/assets/20768148/18421337/efdc8cb2-784d-11e6-9143-70144f047c5d.png)

Update: Files stopped uploading at 2,044
![2016-09-11 3](https://cloud.githubusercontent.com/assets/20768148/18421458/f089b984-7850-11e6-97e7-b80a38ffd04a.png)

**Comment by kernow** [comment]
I have the same issue on OSX but can't get the trace as atom freezes when it happens
